config/routes.rb
Rails.application.routes.draw do
  
  get 'posts/index'

  get 'main/index'
 
  get 'sessions/new'

  get 'about/index'

  get 'home/index'
  root 'home#index'
  resources :users
  
  get 'main/index' => 'main#index', as: :main_page
  resources :sessions
  get 'posts/index' => 'posts#index', as: :posts_main
  
  get 'about/index' => 'about#index', as: :about_main
  
  post 'posts/create' => 'posts#create', as: :posts_create
  
  post 'comments/create' => 'comments#create', as: :comments_create
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :user
   has_many :comments
   
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates_uniqueness_of :email
    has_many :posts
    has_many :comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
   
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
   
  end
  helper_method :current_user

  
  def authorize
    redirect_to new_session_path, alert: "Not authorized" if current_user.nil?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        
        Comment.create(body: params[:body], post_id: params[:post_id], user_id: session[:user_id])
        redirect_to posts_main_path
        
         
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
      
    if current_user
     
       render "loggedinview"
     else
       render "index"
     end
  
       
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
          
    if current_user
     @posts = Post.all
      
     else
      redirect_to new_session_path
     end
    
  end
   def create
     Post.create(title: params[:title], comment: params[:comment], user_id: params[:user_id])
     
     #render text:  params[:post_id] 
    #Post.find_by(params[:user_id]).comments.create(body: params[:comment] )
    redirect_to posts_main_path
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email]) 
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_main_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new" 
    end 
  end
  
  def destroy    
  session[:user_id] = nil    
  redirect_to root_path, notice: "Logged out!"  
  end

end

app/controllers/users_controller.rb
    class UsersController < ApplicationController
  def index
    redirect_to new_user_path
  end
  
  def new
    @user = User.new 
  end   
  
  def create
    @user = User.new(params.require(:user).permit(:email,:password,:password_confirmation))
    if @user.save
      redirect_to root_path, notice: "Thanks for signing up!"
    else
      render "new" 
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
    module ApplicationHelper
    
  def avatar_url(user)
     gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fanblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="jumbotron">
 <div class="other">
    <h1>The New Fantasy Sports Hub</h1>
    <p><strong>Our mission is to transform sports with daily fantasy sport topics and discussions. 
    We're passionate about sports and creating a platform where fans can come to express 
    opinions and daily fantasy picks. Fantasy Sports Blog was created for as a project for a 
    Software Development course at Georgia Gwinnett College.</strong></p>
    
    <br/>
    <br/>
   

  </div>
</div>

<%= yield %>

</body>
</html>

app/views/contact/index.html.erb
<h1>Contact Page</h1>

app/views/home/index.html.erb
<div class="jumbotron">
 <div class="other">
 <strong>
    <h1>Fantasy Sports Talk</h1>
    <h2>The New Fantasy Sports Talk</h2>
    <br/>
    <br/>
</strong>   

  </div>
</div>

app/views/home/loggedinview.html.erb
<div class="jumbotron">
 
 <div class="title">
    <h1>Fantasy Sports Talk</h1>
</div>
    <a style="display:block" href="http://www.dailyfantasysportsrankings.com/">
 

    <div class="daily"style="color:none">
        
     </div>
        
</a>
<a style="display:block" href="https://www.fanduel.com/">
 

    <div class="fanduel"style="color:none">
        
     </div>
        
</a>
</div>

app/views/home/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <ul class="nav navbar-nav">
    <li><%= link_to "Home", '#', id: "logo" %></li>
    <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Log out", '#' %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Talk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link rel="icon" href="favicon.ico" type="image/x-icon" />
</head>
<%= render 'shared/navbar' %>
<%= render 'shared/footer' %>
<body>
  



<%= yield %>

</body>

</html>

app/views/main/index.html.erb
<body>
<div align="center" color="#0066CC">
<h1>Join Conversation</h1>

<h1>Talk Sports</h1>
<%= form_tag  posts_create_path do %>
  <p align="center">
    <%= label_tag :id, "Title"  %>     
       
    <%= text_field_tag "title" %></br>
  </br>
    <%= label_tag :comment, "Comments"  %>  </br>   
    <%= text_area_tag("comment", "" , size: "24x6") %>
    </br>
    <%= submit_tag "Post!" %> 
    </br>
  </p>

<% end %>
</body>

app/views/posts/index.html.erb
<div align="center">
 <div class="">
<h1>Join the Talk</h1>

  
<%= form_tag posts_create_path do %>
<%= label_tag :title, "Title"  %>  </br>

 <div class="panel-heading">
      <h3 class="panel-title">Panel title</h3>
   </div>
 <%= text_field_tag("title") %></br>
<%= label_tag :comment, "Comment"  %>  </br> 
<div class="panel-body">
     
   
<%= text_area_tag("comment", "" , size: "24x6") %>
</div>
<br/>
<%= submit_tag "Comment" %>

<% end %>
</div>

<% @posts.each do |post| %>
<div class="panel panel-default">
<h1><%=post.title%></h1>
</div>
<p> <%= post.comment %>
<% post.comments.each do |comment| %>
 <div class="panel-footer">
<p> <%= comment.body %></p>
</div>
<% end %>
<%= form_tag comments_create_path do %>
<%=hidden_field_tag 'post_id', post.id%>
<%= label_tag :comment, "Comment"  %>  </br>   
<%= text_area_tag("body", "" , size: "24x6") %>
<br/>
<%= submit_tag "Comment" %>

<% end %>
<% end %>
</div>

app/views/shared/_footer.html.erb
<header class="navbar navbar-default navbar-fixed-bottom">
  <ul class="nav nav-tabs">
    <li><%= link_to "Fanduel", 'https://www.fanduel.com/', id: "logo" %></li>
    <li><%= link_to "DraftKings", "https://www.draftkings.com/" %></li>
    <li><%= link_to "Authored by Everton Gardiner", "https://github.com/eagardi" %></li>
  </ul>
</header>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <ul class="nav nav-tabs">
    <li>
      <%=link_to "Home", root_path, id: "logo" %>
    </li>
    <li>
      <%=link_to "About", about_main_path %>
    </li>
    
    <li>
      <%=link_to "Talk", posts_main_path%>
    </li>
    <% if current_user %>
      
      <li>
      <%=link_to "Log Out", session_path( "current"), method: "delete" %>
      </li>
      <li>
        <%=current_user.email %>
      </li>
        <% else %>
          <li>
            <%=link_to "Register", new_user_path %>
            
          </li>
          <li>
                <%=link_to "Login", new_session_path%>
            </li>
          <% end %>

  </ul>
</header>

app/views/users/new.html.erb
<div class="jumbotron">
<div class="container">
<div align="center">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <%= "Error in form" %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
    </ul>
  <% end %>
<h1 align="center">Sign Up</h1>
  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation %><br/>
  <%= f.password_field :password_confirmation %><br/>
  
  <%= f.submit %>
  
<% end %>
</div>
</div>
</div>